// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: knowledge.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDocumentsByKnowledgeBase = `-- name: CountDocumentsByKnowledgeBase :one
SELECT COUNT(*)::bigint
FROM knowledge_documents d
JOIN knowledge_bases kb ON kb.id = d.knowledge_base_id
WHERE d.knowledge_base_id = $1
  AND d.deleted_at IS NULL
  AND kb.deleted_at IS NULL
  AND ($2::boolean OR d.created_by = $3 OR kb.created_by = $3)
  AND ($4::text = '' OR d.status = $4)
`

type CountDocumentsByKnowledgeBaseParams struct {
	KnowledgeBaseID string `json:"knowledge_base_id"`
	CanReadAll      bool   `json:"can_read_all"`
	UserID          string `json:"user_id"`
	Status          string `json:"status"`
}

func (q *Queries) CountDocumentsByKnowledgeBase(ctx context.Context, arg CountDocumentsByKnowledgeBaseParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentsByKnowledgeBase,
		arg.KnowledgeBaseID,
		arg.CanReadAll,
		arg.UserID,
		arg.Status,
	)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countKnowledgeBases = `-- name: CountKnowledgeBases :one
SELECT COUNT(*)::bigint
FROM knowledge_bases kb
WHERE kb.deleted_at IS NULL
  AND ($1::boolean OR kb.created_by = $2)
`

type CountKnowledgeBasesParams struct {
	CanReadAll bool   `json:"can_read_all"`
	UserID     string `json:"user_id"`
}

func (q *Queries) CountKnowledgeBases(ctx context.Context, arg CountKnowledgeBasesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countKnowledgeBases, arg.CanReadAll, arg.UserID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createKnowledgeBase = `-- name: CreateKnowledgeBase :one
INSERT INTO knowledge_bases (
  id,
  name,
  description,
  doc_type,
  chunk_strategy,
  retrieval_strategy,
  created_by,
  created_at,
  updated_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9
)
RETURNING
  id,
  name,
  description,
  doc_type,
  chunk_strategy,
  retrieval_strategy,
  0::bigint AS document_count,
  0::bigint AS chunk_count,
  created_by,
  created_at,
  updated_at,
  deleted_at
`

type CreateKnowledgeBaseParams struct {
	ID                string             `json:"id"`
	Name              string             `json:"name"`
	Description       string             `json:"description"`
	DocType           string             `json:"doc_type"`
	ChunkStrategy     []byte             `json:"chunk_strategy"`
	RetrievalStrategy []byte             `json:"retrieval_strategy"`
	CreatedBy         string             `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type CreateKnowledgeBaseRow struct {
	ID                string             `json:"id"`
	Name              string             `json:"name"`
	Description       string             `json:"description"`
	DocType           string             `json:"doc_type"`
	ChunkStrategy     []byte             `json:"chunk_strategy"`
	RetrievalStrategy []byte             `json:"retrieval_strategy"`
	DocumentCount     int64              `json:"document_count"`
	ChunkCount        int64              `json:"chunk_count"`
	CreatedBy         string             `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) CreateKnowledgeBase(ctx context.Context, arg CreateKnowledgeBaseParams) (CreateKnowledgeBaseRow, error) {
	row := q.db.QueryRow(ctx, createKnowledgeBase,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.DocType,
		arg.ChunkStrategy,
		arg.RetrievalStrategy,
		arg.CreatedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i CreateKnowledgeBaseRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DocType,
		&i.ChunkStrategy,
		&i.RetrievalStrategy,
		&i.DocumentCount,
		&i.ChunkCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDocument = `-- name: GetDocument :one
SELECT
  d.id,
  d.knowledge_base_id,
  d.file_ref,
  d.name,
  d.content_type,
  d.size_bytes,
  d.status,
  d.error_code,
  d.error_message,
  COALESCE(chunk_counts.chunk_count, 0)::bigint AS chunk_count,
  d.tags,
  d.parser_backend,
  d.current_job_id,
  d.created_by,
  d.created_at,
  d.updated_at,
  d.deleted_at
FROM knowledge_documents d
JOIN knowledge_bases kb ON kb.id = d.knowledge_base_id
LEFT JOIN (
  SELECT document_id, COUNT(*)::bigint AS chunk_count
  FROM document_chunks
  GROUP BY document_id
) chunk_counts ON chunk_counts.document_id = d.id
WHERE d.id = $1
  AND d.deleted_at IS NULL
  AND kb.deleted_at IS NULL
  AND ($2::boolean OR d.created_by = $3 OR kb.created_by = $3)
`

type GetDocumentParams struct {
	ID         string `json:"id"`
	CanReadAll bool   `json:"can_read_all"`
	UserID     string `json:"user_id"`
}

type GetDocumentRow struct {
	ID              string             `json:"id"`
	KnowledgeBaseID string             `json:"knowledge_base_id"`
	FileRef         pgtype.Text        `json:"file_ref"`
	Name            string             `json:"name"`
	ContentType     pgtype.Text        `json:"content_type"`
	SizeBytes       pgtype.Int8        `json:"size_bytes"`
	Status          string             `json:"status"`
	ErrorCode       pgtype.Text        `json:"error_code"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	ChunkCount      int64              `json:"chunk_count"`
	Tags            []byte             `json:"tags"`
	ParserBackend   pgtype.Text        `json:"parser_backend"`
	CurrentJobID    pgtype.Text        `json:"current_job_id"`
	CreatedBy       string             `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (GetDocumentRow, error) {
	row := q.db.QueryRow(ctx, getDocument, arg.ID, arg.CanReadAll, arg.UserID)
	var i GetDocumentRow
	err := row.Scan(
		&i.ID,
		&i.KnowledgeBaseID,
		&i.FileRef,
		&i.Name,
		&i.ContentType,
		&i.SizeBytes,
		&i.Status,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.ChunkCount,
		&i.Tags,
		&i.ParserBackend,
		&i.CurrentJobID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getKnowledgeBase = `-- name: GetKnowledgeBase :one
SELECT
  kb.id,
  kb.name,
  kb.description,
  kb.doc_type,
  kb.chunk_strategy,
  kb.retrieval_strategy,
  COALESCE(doc_counts.document_count, 0)::bigint AS document_count,
  COALESCE(chunk_counts.chunk_count, 0)::bigint AS chunk_count,
  kb.created_by,
  kb.created_at,
  kb.updated_at,
  kb.deleted_at
FROM knowledge_bases kb
LEFT JOIN (
  SELECT knowledge_base_id, COUNT(*)::bigint AS document_count
  FROM knowledge_documents
  WHERE deleted_at IS NULL
  GROUP BY knowledge_base_id
) doc_counts ON doc_counts.knowledge_base_id = kb.id
LEFT JOIN (
  SELECT dc.knowledge_base_id, COUNT(*)::bigint AS chunk_count
  FROM document_chunks dc
  JOIN knowledge_documents d ON d.id = dc.document_id
  WHERE d.deleted_at IS NULL
  GROUP BY dc.knowledge_base_id
) chunk_counts ON chunk_counts.knowledge_base_id = kb.id
WHERE kb.id = $1
  AND kb.deleted_at IS NULL
  AND ($2::boolean OR kb.created_by = $3)
`

type GetKnowledgeBaseParams struct {
	ID         string `json:"id"`
	CanReadAll bool   `json:"can_read_all"`
	UserID     string `json:"user_id"`
}

type GetKnowledgeBaseRow struct {
	ID                string             `json:"id"`
	Name              string             `json:"name"`
	Description       string             `json:"description"`
	DocType           string             `json:"doc_type"`
	ChunkStrategy     []byte             `json:"chunk_strategy"`
	RetrievalStrategy []byte             `json:"retrieval_strategy"`
	DocumentCount     int64              `json:"document_count"`
	ChunkCount        int64              `json:"chunk_count"`
	CreatedBy         string             `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetKnowledgeBase(ctx context.Context, arg GetKnowledgeBaseParams) (GetKnowledgeBaseRow, error) {
	row := q.db.QueryRow(ctx, getKnowledgeBase, arg.ID, arg.CanReadAll, arg.UserID)
	var i GetKnowledgeBaseRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DocType,
		&i.ChunkStrategy,
		&i.RetrievalStrategy,
		&i.DocumentCount,
		&i.ChunkCount,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDocumentsByKnowledgeBase = `-- name: ListDocumentsByKnowledgeBase :many
SELECT
  d.id,
  d.knowledge_base_id,
  d.file_ref,
  d.name,
  d.content_type,
  d.size_bytes,
  d.status,
  d.error_code,
  d.error_message,
  COALESCE(chunk_counts.chunk_count, 0)::bigint AS chunk_count,
  d.tags,
  d.parser_backend,
  d.current_job_id,
  d.created_by,
  d.created_at,
  d.updated_at,
  d.deleted_at
FROM knowledge_documents d
JOIN knowledge_bases kb ON kb.id = d.knowledge_base_id
LEFT JOIN (
  SELECT document_id, COUNT(*)::bigint AS chunk_count
  FROM document_chunks
  GROUP BY document_id
) chunk_counts ON chunk_counts.document_id = d.id
WHERE d.knowledge_base_id = $1
  AND d.deleted_at IS NULL
  AND kb.deleted_at IS NULL
  AND ($2::boolean OR d.created_by = $3 OR kb.created_by = $3)
  AND ($4::text = '' OR d.status = $4)
ORDER BY d.created_at DESC, d.id DESC
LIMIT $6 OFFSET $5
`

type ListDocumentsByKnowledgeBaseParams struct {
	KnowledgeBaseID string `json:"knowledge_base_id"`
	CanReadAll      bool   `json:"can_read_all"`
	UserID          string `json:"user_id"`
	Status          string `json:"status"`
	OffsetCount     int32  `json:"offset_count"`
	LimitCount      int32  `json:"limit_count"`
}

type ListDocumentsByKnowledgeBaseRow struct {
	ID              string             `json:"id"`
	KnowledgeBaseID string             `json:"knowledge_base_id"`
	FileRef         pgtype.Text        `json:"file_ref"`
	Name            string             `json:"name"`
	ContentType     pgtype.Text        `json:"content_type"`
	SizeBytes       pgtype.Int8        `json:"size_bytes"`
	Status          string             `json:"status"`
	ErrorCode       pgtype.Text        `json:"error_code"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	ChunkCount      int64              `json:"chunk_count"`
	Tags            []byte             `json:"tags"`
	ParserBackend   pgtype.Text        `json:"parser_backend"`
	CurrentJobID    pgtype.Text        `json:"current_job_id"`
	CreatedBy       string             `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListDocumentsByKnowledgeBase(ctx context.Context, arg ListDocumentsByKnowledgeBaseParams) ([]ListDocumentsByKnowledgeBaseRow, error) {
	rows, err := q.db.Query(ctx, listDocumentsByKnowledgeBase,
		arg.KnowledgeBaseID,
		arg.CanReadAll,
		arg.UserID,
		arg.Status,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsByKnowledgeBaseRow
	for rows.Next() {
		var i ListDocumentsByKnowledgeBaseRow
		if err := rows.Scan(
			&i.ID,
			&i.KnowledgeBaseID,
			&i.FileRef,
			&i.Name,
			&i.ContentType,
			&i.SizeBytes,
			&i.Status,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.ChunkCount,
			&i.Tags,
			&i.ParserBackend,
			&i.CurrentJobID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKnowledgeBases = `-- name: ListKnowledgeBases :many
SELECT
  kb.id,
  kb.name,
  kb.description,
  kb.doc_type,
  kb.chunk_strategy,
  kb.retrieval_strategy,
  COALESCE(doc_counts.document_count, 0)::bigint AS document_count,
  COALESCE(chunk_counts.chunk_count, 0)::bigint AS chunk_count,
  kb.created_by,
  kb.created_at,
  kb.updated_at,
  kb.deleted_at
FROM knowledge_bases kb
LEFT JOIN (
  SELECT knowledge_base_id, COUNT(*)::bigint AS document_count
  FROM knowledge_documents
  WHERE deleted_at IS NULL
  GROUP BY knowledge_base_id
) doc_counts ON doc_counts.knowledge_base_id = kb.id
LEFT JOIN (
  SELECT dc.knowledge_base_id, COUNT(*)::bigint AS chunk_count
  FROM document_chunks dc
  JOIN knowledge_documents d ON d.id = dc.document_id
  WHERE d.deleted_at IS NULL
  GROUP BY dc.knowledge_base_id
) chunk_counts ON chunk_counts.knowledge_base_id = kb.id
WHERE kb.deleted_at IS NULL
  AND ($1::boolean OR kb.created_by = $2)
ORDER BY kb.created_at DESC, kb.id DESC
LIMIT $4 OFFSET $3
`

type ListKnowledgeBasesParams struct {
	CanReadAll  bool   `json:"can_read_all"`
	UserID      string `json:"user_id"`
	OffsetCount int32  `json:"offset_count"`
	LimitCount  int32  `json:"limit_count"`
}

type ListKnowledgeBasesRow struct {
	ID                string             `json:"id"`
	Name              string             `json:"name"`
	Description       string             `json:"description"`
	DocType           string             `json:"doc_type"`
	ChunkStrategy     []byte             `json:"chunk_strategy"`
	RetrievalStrategy []byte             `json:"retrieval_strategy"`
	DocumentCount     int64              `json:"document_count"`
	ChunkCount        int64              `json:"chunk_count"`
	CreatedBy         string             `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListKnowledgeBases(ctx context.Context, arg ListKnowledgeBasesParams) ([]ListKnowledgeBasesRow, error) {
	rows, err := q.db.Query(ctx, listKnowledgeBases,
		arg.CanReadAll,
		arg.UserID,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKnowledgeBasesRow
	for rows.Next() {
		var i ListKnowledgeBasesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DocType,
			&i.ChunkStrategy,
			&i.RetrievalStrategy,
			&i.DocumentCount,
			&i.ChunkCount,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDocumentsDeletedByKnowledgeBase = `-- name: MarkDocumentsDeletedByKnowledgeBase :exec
UPDATE knowledge_documents
SET deleted_at = $1, updated_at = $1
WHERE knowledge_base_id = $2
  AND deleted_at IS NULL
`

type MarkDocumentsDeletedByKnowledgeBaseParams struct {
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	KnowledgeBaseID string             `json:"knowledge_base_id"`
}

func (q *Queries) MarkDocumentsDeletedByKnowledgeBase(ctx context.Context, arg MarkDocumentsDeletedByKnowledgeBaseParams) error {
	_, err := q.db.Exec(ctx, markDocumentsDeletedByKnowledgeBase, arg.DeletedAt, arg.KnowledgeBaseID)
	return err
}

const markKnowledgeBaseDeleted = `-- name: MarkKnowledgeBaseDeleted :execrows
UPDATE knowledge_bases
SET deleted_at = $1, updated_at = $1
WHERE id = $2
  AND deleted_at IS NULL
  AND ($3::boolean OR created_by = $4)
`

type MarkKnowledgeBaseDeletedParams struct {
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	ID         string             `json:"id"`
	CanReadAll bool               `json:"can_read_all"`
	UserID     string             `json:"user_id"`
}

func (q *Queries) MarkKnowledgeBaseDeleted(ctx context.Context, arg MarkKnowledgeBaseDeletedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markKnowledgeBaseDeleted,
		arg.DeletedAt,
		arg.ID,
		arg.CanReadAll,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateKnowledgeBase = `-- name: UpdateKnowledgeBase :execrows
UPDATE knowledge_bases
SET
  name = $1,
  description = $2,
  doc_type = $3,
  chunk_strategy = $4,
  retrieval_strategy = $5,
  updated_at = $6
WHERE id = $7
  AND deleted_at IS NULL
  AND ($8::boolean OR created_by = $9)
`

type UpdateKnowledgeBaseParams struct {
	Name              string             `json:"name"`
	Description       string             `json:"description"`
	DocType           string             `json:"doc_type"`
	ChunkStrategy     []byte             `json:"chunk_strategy"`
	RetrievalStrategy []byte             `json:"retrieval_strategy"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ID                string             `json:"id"`
	CanReadAll        bool               `json:"can_read_all"`
	UserID            string             `json:"user_id"`
}

func (q *Queries) UpdateKnowledgeBase(ctx context.Context, arg UpdateKnowledgeBaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateKnowledgeBase,
		arg.Name,
		arg.Description,
		arg.DocType,
		arg.ChunkStrategy,
		arg.RetrievalStrategy,
		arg.UpdatedAt,
		arg.ID,
		arg.CanReadAll,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
