// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DocumentChunk struct {
	ID                 string             `json:"id"`
	KnowledgeBaseID    string             `json:"knowledge_base_id"`
	DocumentID         string             `json:"document_id"`
	ChunkIndex         int32              `json:"chunk_index"`
	SectionPath        pgtype.Text        `json:"section_path"`
	Content            string             `json:"content"`
	TokenCount         pgtype.Int4        `json:"token_count"`
	ChunkType          pgtype.Text        `json:"chunk_type"`
	QdrantPointID      pgtype.Text        `json:"qdrant_point_id"`
	EmbeddingProvider  pgtype.Text        `json:"embedding_provider"`
	EmbeddingModel     pgtype.Text        `json:"embedding_model"`
	EmbeddingDimension pgtype.Int4        `json:"embedding_dimension"`
	Metadata           []byte             `json:"metadata"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type KnowledgeBasis struct {
	ID                string             `json:"id"`
	Name              string             `json:"name"`
	Description       string             `json:"description"`
	DocType           string             `json:"doc_type"`
	ChunkStrategy     []byte             `json:"chunk_strategy"`
	RetrievalStrategy []byte             `json:"retrieval_strategy"`
	CreatedBy         string             `json:"created_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type KnowledgeDocument struct {
	ID              string             `json:"id"`
	KnowledgeBaseID string             `json:"knowledge_base_id"`
	FileRef         pgtype.Text        `json:"file_ref"`
	Name            string             `json:"name"`
	ContentType     pgtype.Text        `json:"content_type"`
	SizeBytes       pgtype.Int8        `json:"size_bytes"`
	Status          string             `json:"status"`
	ErrorCode       pgtype.Text        `json:"error_code"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	Tags            []byte             `json:"tags"`
	ParserBackend   pgtype.Text        `json:"parser_backend"`
	CurrentJobID    pgtype.Text        `json:"current_job_id"`
	CreatedBy       string             `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type ProcessingJob struct {
	ID              string             `json:"id"`
	KnowledgeBaseID string             `json:"knowledge_base_id"`
	DocumentID      pgtype.Text        `json:"document_id"`
	JobType         string             `json:"job_type"`
	Status          string             `json:"status"`
	CurrentStage    pgtype.Text        `json:"current_stage"`
	ProgressPercent int32              `json:"progress_percent"`
	Message         pgtype.Text        `json:"message"`
	ErrorCode       pgtype.Text        `json:"error_code"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	Attempts        int32              `json:"attempts"`
	MaxAttempts     int32              `json:"max_attempts"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	FinishedAt      pgtype.Timestamptz `json:"finished_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
