/**
 * Shared TypeScript types aligned with the Gateway OpenAPI specification.
 *
 * All API entity types are re-exported from `@/api/generated/gateway`
 * (the authoritative source generated by openapi-typescript).
 *
 * UI-only types (theme, navigation, etc.) and SSE payload data types
 * are defined here since they are not part of the gateway contract.
 */

import type { components } from '@/api/generated/gateway'

// =============================================================================
// Re-exports from generated/gateway (authoritative API types)
// =============================================================================

// ── Common ──
export type PageInfo = components['schemas']['PageInfo']

// ── Auth ──
export type UserSummary = components['schemas']['UserSummary']
export type SessionSummary = components['schemas']['SessionSummary']
export type CreateUserRequest = components['schemas']['CreateUserRequest']
export type CreateSessionRequest = components['schemas']['CreateSessionRequest']

// ── QA Sessions ──
export type QASessionStatus = components['schemas']['QASessionStatus']
export type QASession = components['schemas']['QASession']
/** Alias: the OpenAPI spec uses the same QASession schema for both detail and list items. */
export type QASessionListItem = components['schemas']['QASession']
export type CreateQASessionRequest = components['schemas']['CreateQASessionRequest']
export type UpdateQASessionRequest = components['schemas']['UpdateQASessionRequest']

// ── QA Messages ──
export type QAMessageRole = components['schemas']['QAMessageRole']
export type QAMessageStatus = components['schemas']['QAMessageStatus']
export type QAIntent = components['schemas']['QAIntent']
export type QAMessage = components['schemas']['QAMessage']
export type QARetrievalOptions = components['schemas']['QARetrievalOptions']
export type QAAgentOptions = components['schemas']['QAAgentOptions']
export type CreateQAMessageRequest = components['schemas']['CreateQAMessageRequest']

// ── QA Thinking Steps ──
export type QAThinkingStep = components['schemas']['QAThinkingStep']

// ── QA Citations ──
export type QACitation = components['schemas']['QACitation']
export type QACitationDetail = components['schemas']['QACitationDetail']
export type CreateQACitationLookupRequest = components['schemas']['CreateQACitationLookupRequest']

// ── QA Response Runs ──
export type QAResponseRunStatus = components['schemas']['QAResponseRunStatus']
export type QAResponseRun = components['schemas']['QAResponseRun']
export type UpdateQAResponseRunRequest = components['schemas']['UpdateQAResponseRunRequest']

// ── QA Agent Tool Calls ──
export type QAAgentToolCall = components['schemas']['QAAgentToolCall']

// ── QA SSE Events ──
export type QASseEventType = components['schemas']['QASseEventType']
export type QASseEvent = components['schemas']['QASseEvent']

// ── Knowledge Bases ──
export type ChunkStrategy = components['schemas']['ChunkStrategy']
export type RetrievalStrategy = components['schemas']['RetrievalStrategy']
export type KnowledgeBaseSummary = components['schemas']['KnowledgeBaseSummary']
export type CreateKnowledgeBaseRequest = components['schemas']['CreateKnowledgeBaseRequest']
export type UpdateKnowledgeBaseRequest = components['schemas']['UpdateKnowledgeBaseRequest']

// ── Documents ──
export type DocumentStatus = components['schemas']['DocumentStatus']
export type DocumentSummary = components['schemas']['DocumentSummary']
export type UpdateDocumentRequest = components['schemas']['UpdateDocumentRequest']
export type DocumentChunk = components['schemas']['DocumentChunk']

// ── Knowledge Queries ──
export type KnowledgeQueryRequest = components['schemas']['KnowledgeQueryRequest']
export type KnowledgeQueryResult = components['schemas']['KnowledgeQueryResult']
export type KnowledgeQueryTrace = components['schemas']['KnowledgeQueryTrace']
export type KnowledgeQuerySummary = components['schemas']['KnowledgeQuerySummary']

// ── Admin: Model Profiles ──
export type ModelPurpose = components['schemas']['ModelPurpose']
export type ModelProvider = components['schemas']['ModelProvider']
export type ModelProfile = components['schemas']['ModelProfile']
export type CreateModelProfileRequest = components['schemas']['CreateModelProfileRequest']
export type UpdateModelProfileRequest = components['schemas']['UpdateModelProfileRequest']

// ── Admin: Parser Configs ──
export type ParserBackend = components['schemas']['ParserBackend']
export type ParserConfig = components['schemas']['ParserConfig']
export type CreateParserConfigRequest = components['schemas']['CreateParserConfigRequest']
export type UpdateParserConfigRequest = components['schemas']['UpdateParserConfigRequest']

// ── QA Config / LLM Config ──
export type QALLMConfigVersion = components['schemas']['QALLMConfigVersion']
export type CreateQALLMConfigVersionRequest = components['schemas']['CreateQALLMConfigVersionRequest']
export type QAAgentConfig = components['schemas']['QAAgentConfig']
export type QAConfigKnowledgeBase = components['schemas']['QAConfigKnowledgeBase']
export type QAConfigVersion = components['schemas']['QAConfigVersion']
export type CreateQAConfigVersionRequest = components['schemas']['CreateQAConfigVersionRequest']
export type QALLMConnectionTestRequest = components['schemas']['CreateQALLMConnectionTestRequest']
export type QALLMConnectionTest = components['schemas']['QALLMConnectionTest']

// ── QA Retrieval Test ──
export type QARetrievalTestRunRequest = components['schemas']['CreateQARetrievalTestRunRequest']
export type QARetrievalTestResult = components['schemas']['QARetrievalTestResult']
export type QARetrievalTestRun = components['schemas']['QARetrievalTestRun']

// ── QA Metrics ──
export type QAMetricsOverview = components['schemas']['QAMetricsOverview']
export type QAMetricsTrendPoint = components['schemas']['QAMetricsTrendPoint']
export type QAMetricsTrend = components['schemas']['QAMetricsTrend']
export type QATopQuery = components['schemas']['QATopQuery']
export type QAIntentDistributionItem = components['schemas']['QAIntentDistributionItem']

// =============================================================================
// UI-only types (not in generated/gateway)
// =============================================================================

/** Admin sidebar navigation item. */
export interface AdminMenuItem {
  key: string
  label: string
  icon?: string
  path?: string
  children?: AdminMenuItem[]
}

// =============================================================================
// SSE data payload types (UI event shapes not part of the gateway contract)
// =============================================================================

export interface MessageCreatedData {
  messageId: string
  sessionId: string
  responseRunId: string
  sequenceNo: number
}

export interface AgentIterationStartedData {
  responseRunId: string
  iterationNo: number
}

export interface ReasoningStepData {
  responseRunId: string
  step: QAThinkingStep
}

export interface ToolStartedData {
  responseRunId: string
  toolCallId: string
  toolName: string
}

export interface ToolCompletedData {
  responseRunId: string
  toolCallId: string
  toolName: string
  latencyMs: number
}

export interface ToolFailedData {
  responseRunId: string
  toolCallId: string
  toolName: string
  errorCode: string
  errorMessage: string
}

export interface AnswerDeltaData {
  responseRunId: string
  content: string
  sequenceNo: number
}

export interface CitationDeltaData {
  responseRunId: string
  citation: QACitation
}

export interface AnswerCompletedData {
  responseRunId: string
  assistantMessageId: string
  totalTokens: number
  latencyMs: number
}

export interface SSEErrorData {
  responseRunId?: string
  code: string
  message: string
  fatal: boolean
}

// =============================================================================
// Backward-compatibility aliases
//
// Map old frontend type names to new OpenAPI-aligned names.
// Consumers can migrate incrementally.
// =============================================================================

/** @deprecated Use `QASession` instead. */
export type Conversation = QASession

/** @deprecated Use `QASessionListItem` instead. */
export type ConversationListItem = QASessionListItem

/** @deprecated Use `QAMessage` instead. */
export type Message = QAMessage

/** @deprecated Use `QAThinkingStep` instead. */
export type ThinkingStep = QAThinkingStep

/** @deprecated Use `QACitation` instead. */
export type Citation = QACitation

/** @deprecated Use `CreateQAMessageRequest` instead. */
export type ChatStreamRequest = CreateQAMessageRequest

/** @deprecated Use `QAIntent` instead. */
export type IntentType = QAIntent

/** @deprecated Use `QAMetricsOverview` instead. */
export type StatsOverview = QAMetricsOverview

/** @deprecated Use `QAMetricsTrendPoint` instead. */
export type TrendPoint = QAMetricsTrendPoint

/** @deprecated Use `QATopQuery` instead. */
export type TopQuery = QATopQuery

// ── Deprecated SSE types (backward compat) ──

/** @deprecated Use QASseEventType instead. */
export type QAMessageEventType = QASseEventType

/** @deprecated Use QASseEventType instead. */
export type SSEEventType = QASseEventType

/** @deprecated Use ReasoningStepData + QAThinkingStep types instead. */
export interface SSEIntentStatusData {
  status: 'started' | 'done'
  label: string
  intent?: QAIntent
  confidence?: number
  seq: number
}

/** @deprecated Use ReasoningStepData instead. */
export interface SSEThinkingStepData {
  step: QAThinkingStep
  seq: number
}

/** @deprecated Use AnswerDeltaData instead. */
export interface SSETokenData {
  text: string
  index: number
  seq: number
}

/** @deprecated Use CitationDeltaData instead. */
export interface SSECitationData {
  citation: QACitation
  seq: number
}

/** @deprecated Use AnswerCompletedData instead. */
export interface SSEDoneData {
  messageId: string
  assistantMessageId?: string
  totalTokens: number
  promptTokens?: number
  completionTokens?: number
  latencyMs: number
  seq: number
}

// ── Deprecated RAG types (backward compat) ──

/** @deprecated Use KnowledgeQueryRequest instead. */
export interface RAGSearchRequest {
  query: string
  knowledgeBaseIds?: string[]
  topK?: number
  similarityThreshold?: number
  useRerank?: boolean
  rerankThreshold?: number
  rerankTopN?: number
}

/** @deprecated Use KnowledgeQueryResult instead. */
export interface RAGSearchResult {
  rank: number
  chunkId: string
  documentId: string
  documentName: string
  contentPreview: string
  vectorScore: number
  rerankScore?: number
  pageNumber?: number
  chunkIndex?: number
}

// ── Deprecated config types (backward compat) ──

/** @deprecated Use KnowledgeBaseSummary instead. */
export interface KnowledgeBaseConfig {
  id: string
  name: string
  docCount: number
  status: 'active' | 'inactive'
}

/** @deprecated Use QARetrievalOptions instead. */
export interface RAGDefaults {
  knowledgeBases: string[]
  topK: number
  similarityThreshold: number
  useRerank: boolean
  rerankThreshold: number
  rerankTopN: number
}

/**
 * @deprecated Use QALLMConfigVersion instead.
 * Note: the OpenAPI spec no longer exposes apiUrl/apiKey on public
 * LLM config — those are owned by AI Gateway model profiles.
 */
export interface LLMConfig {
  apiUrl: string
  apiKey: string
  modelName: string
  timeout: number
  temperature: number
  maxTokens: number
}

// ── Deprecated document types (backward compat) ──

/** @deprecated Use DocumentSummary instead. */
export interface DocumentUploadResponse {
  docId: string
  filename: string
  fileSize: number
  status: DocumentStatus
  knowledgeBase: string
  uploadedAt: string
}

/** @deprecated Use DocumentSummary.status instead. */
export interface DocumentStatusResponse {
  docId: string
  status: DocumentStatus
  progress: {
    step: string
    current: number
    total: number
    percent: number
  }
  error: string | null
}

/** @deprecated Use QAIntent type directly. */
export interface IntentResult {
  intent: QAIntent
  label: string
  confidence: number
  reasoning?: string
}

// =============================================================================
// Deprecated type aliases for old list-style types
// =============================================================================

/** @deprecated Use PageInfo from generated instead. */
export type ListResult<T> = {
  items: T[]
  total: number
  page: number
  pageSize: number
}

/** @deprecated Use QARetrievalTestRunRequest instead. */
export type QAThinkingStepType =
  'agent_iteration' | 'tool_call' | 'tool_result' | 'generation' | 'citation' | 'verify'

/** @deprecated Use QAThinkingStep['status'] or the generated type. */
export type QAThinkingStepStatus = 'pending' | 'running' | 'done' | 'failed'

/** @deprecated Use QAResponseRun['terminationReason'] or the generated type. */
export type QATerminationReason =
  | 'completed'
  | 'max_iterations'
  | 'timeout'
  | 'cancelled'
  | 'tool_error'
  | 'model_error'
  | 'policy_denied'

/** @deprecated Use QAAgentToolCall['status'] or the generated type. */
export type QAAgentToolCallStatus = 'running' | 'completed' | 'failed' | 'cancelled'

/** @deprecated Use the generated ReportStatus instead. */
export type ReportStatus =
  | 'draft'
  | 'outline_generating'
  | 'outline_generated'
  | 'content_generating'
  | 'generated'
  | 'exporting'
  | 'exported'
  | 'failed'
  | 'deleted'

/** @deprecated Use the generated ReportJobStatus instead. */
export type ReportJobStatus =
  'pending' | 'running' | 'succeeded' | 'partial_succeeded' | 'failed' | 'canceled'

/** @deprecated Use the generated ReportJobType instead. */
export type ReportJobType =
  | 'outline_generation'
  | 'outline_regeneration'
  | 'content_generation'
  | 'content_regeneration'
  | 'section_regeneration'
  | 'report_file_creation'

/** @deprecated Use generated report types. */
export interface ReportType {
  code: string
  name: string
  description?: string
  enabled: boolean
  defaultTemplateId?: string
}

/** @deprecated Use generated report types. */
export interface ReportTemplate {
  id: string
  templateName: string
  reportType: string
  version: number
  description?: string
  enabled: boolean
  filename?: string
  fileSize?: number
  createdBy?: string
  createdAt: string
  updatedAt?: string
}

/** @deprecated Use generated report types. */
export interface Report {
  id: string
  name: string
  reportType: string
  templateId?: string
  topic?: string
  specialty?: string
  businessObject?: string
  year?: number
  status: ReportStatus
  extraContext?: Record<string, unknown>
  creatorId?: string
  creatorName?: string
  source?: string
  latestJobId?: string
  latestReportFileId?: string
  generatedAt?: string
  exportedAt?: string
  createdAt: string
  updatedAt?: string
}

/** @deprecated Use generated report types. */
export interface ReportJob {
  id: string
  reportId: string
  templateId?: string
  jobType: ReportJobType
  targetType?: string
  targetId?: string
  status: ReportJobStatus
  progress?: Record<string, unknown>
  resultSummary?: string
  error?: ReportJobError
  startedAt?: string
  finishedAt?: string
  createdAt: string
}

/** @deprecated Use generated types. */
export interface ReportJobError {
  code?: string
  message?: string
}

/** @deprecated Use generated report types. */
export interface ReportFile {
  id: string
  reportId: string
  jobId?: string
  filename?: string
  format: 'docx'
  fileSize?: number
  status: ReportJobStatus
  contentPath?: string
  createdBy?: string
  createdAt: string
}
